/*
 * This source file was generated by the Gradle 'init' task
 */
package bcc.unitConverter;

// import org.junit.Test; // Unused import removed
// import static org.junit.Assert.*; // Unused import removed

public class AppTest {
    // @Test public void appHasAGreeting() {
    //     App classUnderTest = new App();
    //     assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    // }
}
