/*
 * This source file was generated by the Gradle 'init' task
 */

package bcc.unitConverter;

import javax.swing.JFrame;
// 
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.JButton;
import java.awt.GridLayout;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
// import javax.swing.JFrame; // Duplicate unused import removed

public class App {
    public static void main(String[] args) {
        JFrame frame = new JFrame("Unit Converter");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

    //
    frame.setLayout(new GridLayout(3, 4, 5, 5));

        JLabel inputLabel1 = new JLabel("Fahrenheit:");
        JTextField inputField1 = new JTextField();
        JButton convertButton1 = new JButton("Convert");
        JLabel outputLabel1 = new JLabel("Celsius: ");

        convertButton1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                try {
                    double fahrenheit = Double.parseDouble(inputField1.getText());
                    double celsius = (fahrenheit - 32) * 5 / 9;
                    
                    outputLabel1.setText(String.format("Celsius: %.2f", celsius));
                } catch (NumberFormatException ex) {
                    outputLabel1.setText("Celsius: Invalid input");
                }
            }
        });

        frame.add(inputLabel1);
        frame.add(inputField1);
        frame.add(convertButton1);
        frame.add(outputLabel1);

        //
        JLabel inputLabel2 = new JLabel("Celsius:");
        JTextField inputField2 = new JTextField();
        JButton convertButton2 = new JButton("Convert");
        JLabel outputLabel2 = new JLabel("Fahrenheit: ");

        convertButton2.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                try {
                    double celsius = Double.parseDouble(inputField2.getText());
                    double fahrenheit = (celsius * 9 / 5) + 32;
                    outputLabel2.setText(String.format("Fahrenheit: %.2f", fahrenheit));
                } catch (NumberFormatException ex) {
                    outputLabel2.setText("Fahrenheit: Invalid input");
                }
            }
        });

        // --- Row 3: Apples to Bananas (imaginary) ---
        JLabel inputLabel3 = new JLabel("Apples:");
        JTextField inputField3 = new JTextField();
        JButton convertButton3 = new JButton("Convert");
        JLabel outputLabel3 = new JLabel("Bananas: ");

        convertButton3.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                try {
                    double apples = Double.parseDouble(inputField3.getText());
                    double bananas = apples * 2; // 1 apple = 2 bananas
                    outputLabel3.setText(String.format("Bananas: %.2f", bananas));
                } catch (NumberFormatException ex) {
                    outputLabel3.setText("Bananas: Invalid input");
                }
            }
        });

        // co
        frame.add(inputLabel1);
        frame.add(inputField1);
        frame.add(convertButton1);
        frame.add(outputLabel1);

        frame.add(inputLabel2);
        frame.add(inputField2);
        frame.add(convertButton2);
        frame.add(outputLabel2);

        frame.add(inputLabel3);
        frame.add(inputField3);
        frame.add(convertButton3);
        frame.add(outputLabel3);

        // 
        frame.setSize(500, 220);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }

}
